language: rust
rust:
  - stable
#  - 1.31.0
#  - 1.22.0
before_script:
  - rustup component add rustfmt
  - aclocal --version
  - cd libevent-sys/libevent-*
  - autoreconf --force --install
  - cd ../../
  - cd tor-tor-*
  - sh autogen.sh
  - cd ../
script:
  - cargo fmt -- --check --verbose
  - cargo test -vv

notifications:
  email: false
