[package]
name = "libtor-sys"
version = "0.1.0"
authors = ["Alekos Filini <alekos.filini@gmail.com>"]
edition = "2018"
build = "build.rs"
links = "tor"

[dependencies]
openssl-sys = { version = "0.9.53", features = ["vendored"] }
libz-sys = { version = "1.0.25", features = ["static"] }
libevent-sys = { version = "0.1.0", path = "./libevent-sys" }

[build-dependencies]
cc = "1.0"
autotools = "0.2"

[lib]
name = "tor_sys"
path = "src/lib.rs"
