[package]
name = "libtor-sys"
version = "42.7.0+0.4.2.7"
authors = ["Alekos Filini <alekos.filini@gmail.com>"]
license = "MIT"
homepage = "https://github.com/MagicalBitcoin/libtor-sys"
repository = "https://github.com/MagicalBitcoin/libtor-sys"
documentation = "https://docs.rs/libtor-sys/"
description = "Rust crate that internally compiles Tor and its dependencies"
keywords = ["tor", "daemon"]
readme = "README.md"

build = "build.rs"
links = "tor"

[dependencies]
openssl-sys = { version = "0.9", features = ["vendored"] }
libz-sys = { version = "1.0", features = ["static"] }

[build-dependencies]
cc = "1.0"
autotools = "0.2"
fs_extra = "1.1"

[lib]
name = "tor_sys"
path = "src/lib.rs"
